CREATE  TABLE users (
  username VARCHAR(45) NOT NULL ,
  password VARCHAR(145) NOT NULL ,
  enabled TINYINT NOT NULL DEFAULT 1 ,
  PRIMARY KEY (username));
   
CREATE TABLE user_roles (
  user_role_id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(45) NOT NULL,
  role varchar(45) NOT NULL,
  PRIMARY KEY (user_role_id),
  UNIQUE KEY uni_username_role (role,username),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username));
  
CREATE TABLE COMPUTER_CONFIG (COMPUTER_ID bigint auto_increment, 
COMPUTER_NAME VARCHAR(255), DATE_OF_DATA VARCHAR(255), PRIMARY KEY (COMPUTER_ID));

CREATE TABLE MAC_AND_IP(MAC_AND_IP_ID bigint auto_increment, PARENT_COMPUTER_ID INTEGER NOT NULL,
COMPUTER_NAME varchar(50), MAC_ADDRESS varchar(50), IP_ADDRESS varchar(50), START_TIME VARCHAR(50), END_TIME varchar(50),
PRIMARY KEY (MAC_AND_IP_ID),
CONSTRAINT fk_computer_id FOREIGN KEY (PARENT_COMPUTER_ID) REFERENCES COMPUTER_CONFIG (COMPUTER_ID));
